version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=simulador_banco
     - POSTGRES_USER=thaynara.silva
     - POSTGRES_PASSWORD=12345678
     - MAX_CONNECTIONS=300

    volumes:
     - ./docker-compose-postgres.sql:/docker-entrypoint-initdb.d/setup.sql